### ISSUE TITLE
Wrong subnet name

### ISSUE THREAD

**Issue by tsunami28** [Azure/ato-toolkit#25]
"Subnet: The subnet in your virtual network where the new Bastion host will be deployed. The subnet will be dedicated to the Bastion host and must be named as **AzureBastionSubnet**. This subnet must be at least /27 or larger."

The current name in *\automation\zero-trust-architecture\blueprint\artifacts\net.json is just "bastion".
Connected issues:
*\automation\zero-trust-architecture\blueprint\artifacts\jumpbox.json has variable using wrong name.
*\automation\zero-trust-architecture\blueprint\artifacts\keyvault.json has variable using wrong name.

**Comment by sdubeymsft** [comment]
@tsunami28- Thank you for feedback and reaching out. We were not intending to use the subnet to deploy Azure Bastion service into it and instead were using a VM based Jump Box, however, we do recognize the naming confusion it has created and have addressed this is in v2 iteration of the code.
