### ISSUE TITLE
Jumbox subnet association

### ISSUE THREAD

**Issue by tsunami28** [Azure/ato-toolkit#26]
The artifact 'jumpbox' of type 'Template' failed to deploy due to the following error: Template deployment failed with error [ { "code": "AzureBastionSubnet", "message": "Subnet with name 'AzureBastionSubnet' can be used only for the Azure Bastion resource." } ]
By the documentation it is not allowed to add anything in Bastion subnet, so no VM nic.

```json
{
          "type": "Microsoft.Network/networkInterfaces",
          "apiVersion": "2017-09-01",
          "condition": "[equals(parameters('jumpbox-os'), 'Windows')]",
          "location": "[resourceGroup().location]",
          "name": "[concat(variables('windows-virtualMachine-name-prefix'), '-bastion-nic')]",
          "properties": {
            "ipConfigurations": [
              {
                "name": "ipconfig1",
                "properties": {
                  "privateIPAllocationMethod": "Dynamic",
                  "subnet": {
                    "id": "[variables('bastion-subnet-id')]"
                  }
                }
              }
            ]
          }
        },
```

**Comment by tsunami28** [comment]
If the intention was to create Bastion Host, you have to use ""type": "Microsoft.Network/bastionHosts"" and not ""type": "Microsoft.Compute/virtualMachines""

**Comment by sdubeymsft** [comment]
@tsunami28- Thank you for feedback and reaching out. You are right, we didn't pick the subnet names correctly and in fact should have never used 'Bastion' as we are creating a VM based hop/Jump Box. We have addressed this is in v2 iteration of the code.
