### ISSUE TITLE
ubuntuSTIG.sh not explicitly setting file permissions on newly created files

### ISSUE THREAD

**Issue by senterfd-jrg** [Azure/ato-toolkit#57]
The ubuntuSTIG.sh backs up two files (backup.common-password and backup.common-auth) and creates two new files. The two new files are created using output redirection. The current configuration is relying on the "umask" settings to set the new file's permissions. This is not a recommended approach and is causing my configuration to stop working. In my case, I have added the following two commands to ensure the permissions are set appropriately for operation.

https://github.com/Azure/ato-toolkit/blob/e63f31cadf6f1347749538546cddee58765b795e/stig/linux/ubuntuSTIG.sh#L27-L33
`chmod 644 /etc/pam.d/common-password`

https://github.com/Azure/ato-toolkit/blob/e63f31cadf6f1347749538546cddee58765b795e/stig/linux/ubuntuSTIG.sh#L34-L44
`chmod 644 /etc/pam.d/common-auth`

**Comment by bcwilhite** [comment]
Hi @senterfd-jrg, thanks for opening an issue.  This solution is designed to run on a newly deployed Ubuntu 18.04 image from Azure.  When I repro the issue, both files appear to have 644 as shown in the screenshot.  Are you running this solution on a newly deployed Ubuntu 18.04 Azure Image?
![ReproScreenshot](https://user-images.githubusercontent.com/12042836/121224981-0f56f880-c857-11eb-9190-f21b48e66e32.jpg)

**Comment by bcwilhite** [comment]
Closing issue as behavior is expected given solution is within STIG guidance post VM deployment.  Can reopen issue if proved otherwise.
